### ISSUE TITLE
package breaking the index

### ISSUE THREAD

**Issue by angerman** [andreabedini/foliage#14]
So I've pushed everything(!) from Plutus into my hackage... and the build broke.

```
Creating source distribution for fomega-0.1.0.0.0.0.0.0.1
# cabal (for _repo/package/fomega-0.1.0.0.0.0.0.0.1.tar.gz)
cabal: Spec.hs doesn't exist
foliage: Error when running Shake build system:
  at want, called at app/Foliage/CmdBuild.hs:164:7 in main:Foliage.CmdBuild
* Depends on: _repo/timestamp.json
* Depends on: _repo/snapshot.json
* Depends on: _repo/01-index.tar
  at need, called at app/Foliage/Shake.hs:22:28 in main:Foliage.Shake
* Depends on: _repo/index/fomega/0.1.0.0.0.0.0.0.1/package.json
  at need, called at app/Foliage/Shake.hs:18:3 in main:Foliage.Shake
* Depends on: _repo/package/fomega-0.1.0.0.0.0.0.0.1.tar.gz
  at cmd_, called at app/Foliage/CmdBuild.hs:418:11 in main:Foliage.CmdBuild
* Raised the exception:
Development.Shake.cmd, system command failed
```
this is _after_ the check. 

I then tried to just delete the `meta.toml` from the repo, but then the check phase failed.
I had to git rebase, drop the bad package commit (well the package is bad) and the bad delete commit, and force-push to get it back working.

**Comment by andreabedini** [comment]
Thanks @angerman, that's an interesting error :D cabal must be failing at creating the sdist. Would you have a link the relevant fomega commit?

**Comment by andreabedini** [comment]
> this is after the check

note that downstream users were oblivious to the whole process, since if the build fails the index doesn't get updated.

**Comment by andreabedini** [comment]
My understanding is that something was wrong with the fomega source distribution. Feel free to reopen if you think there's more to it.
