### ISSUE TITLE
Also generate static site

### ISSUE THREAD

**Issue by phadej** [andreabedini/foliage#16]
AFAIU `foliage` only generates the index,

but it would be useful if it generated the website part (c.f. Hackage) so one can browse which packages are there (and maybe look some metadata about them, like version bounds etc.).

Haddocks would be great, but I'm explicitly not asking for that. The metadata can be presented already based on what is in the index, so that information should be available relatively easily.

**Comment by michaelpj** [comment]
Andrea is way ahead of you :) https://github.com/andreabedini/foliage/pull/15

It would be very nice to have Haddock, but that is a lot more complicated indeed.

**Comment by andreabedini** [comment]
I'll never be ahead of @phadej, at best I am catching up with 2015's version of Oleg ;-)
@phadej please feel free to leave any comment or ideas in #15.

**Comment by andreabedini** [comment]
Implemented in 4dcd18ac387c9367390675d4f43e4685d6f67a6f
