### ISSUE TITLE
Is foliage parallel?

### ISSUE THREAD

**Issue by michaelpj** [andreabedini/foliage#17]
Does foliage do its work in parallel? It seems like a lot of it should be parallelizable, and it's using Shake under the hood, so maybe it just works? Maybe we just need to tell shake to use multiple threads somewhere?

**Comment by andreabedini** [comment]
Parallelism should not be hard to achieve. Placing the right combinators here and there should get us most of the way there,

**Comment by michaelpj** [comment]
Yeah, this just popped into my head. I don't think our repositories are big enough that this is a problem, but over time it might become valuable.

**Comment by michaelpj** [comment]
I noticed that building the repo from scratch now spends a decent amount of time downloading things in sequence. It would probably be good to do downloading in parallel, if possible.

**Comment by andreabedini** [comment]
Closed in #29
