### ISSUE TITLE
Remove frontend paging from generated listings.

### ISSUE THREAD

**Issue by phadej** [andreabedini/foliage#24]
The pages are small. Even hackage manages to list all packages on one page (https://hackage.haskell.org/packages/)
Make Ctrl+F work.

With current paging one cannot quickly search a package. Cannot link to a particular page either. It's fancy, but not very usable. Please generate *static* pages.

**Comment by andreabedini** [comment]
I wouldn't mind removing the javascript table but I am wondering exactly what issue you are running into.
1. There's a searchbox at the top which you can use to quickly search a package. (It's also linkable e.g. https://input-output-hk.github.io/cardano-haskell-packages/all-packages/?q=b6ab4ca226ba541ee89374a30824351a91285226 although I didn't document this).
2. You can click on "Show all entries" on the top left if you want to see all entries at once and use your browser search.
3. You can link to a particular page (e.g. https://input-output-hk.github.io/cardano-haskell-packages/package/byron-spec-chain-0.1.1.2/). PS: oh, you mean pagination page ... I didn't think of that
4. All the page content is actually served statically, the javascript only reshuffles and hids things. In particular, I wanted to be able to sort it either by package name or by timestamp. You can open it with `links` and it will work (I just tested it).
 
What am I missing?

**Comment by andreabedini** [comment]
> I pose a counter question: What value does dynamic JavaScript based page adds in comparison to plain old HTML table.

The ability to sort by a given column with a page refresh.

> Make the page usable without JavaScript. Then it can be "enhanced" by JS, but JS shouldn't be a requirement.

I am sorry but this is exactly what it does. Look a the source, the table is there. It can be used without Javascript. Javascript only adds non-essential funtionality.

I take that you don't like the funtionality that Javascript adds, and that's fine.
