### ISSUE TITLE
`foliage sdist <pkg-id>`

### ISSUE THREAD

**Issue by michaelpj** [andreabedini/foliage#43]
It would be handy to be able to get the source distribution for a single package. That lets you a) check that it looks right, b) get the final cabal file that foliage will use.

b) is especially helpful if you want to do a revision: you want to start from the current "latest" cabal file. Doing this yourself (even in a script) is annoying: you need to parse the metadata file, download the source archive, find the cabal file, apply the existing revisions. Annoying. Much nicer if we could just ask foliage for the latest cabal file (which we can get from the sdist).

**Comment by michaelpj** [comment]
Ignore this, I don't actually want the sdist, I want the final cabal file, which isn't even in the sdist.

**Comment by andreabedini** [comment]
I'll close this for now. Maybe we can open another issue to design the workflow of making a revision.
