### ISSUE TITLE
Ideas from Hamish

### ISSUE THREAD

**Issue by andreabedini** [andreabedini/foliage#6]
From @hamishmack on Slack
> Just a thought, but a git commit hook for repos like byo-hackage do some nice sanity checks:
Verify that all existing timestamps < all new timestamps <= current time
Prohibit modification of existing files.
> Perhaps even add timestamps if not present.

**Comment by michaelpj** [comment]
If we're going to do timestamp checking then I think it might make more sense to do it in CI, and only allow fast-forward merges. Although that would push most of the annoying work onto contributors.

**Comment by andreabedini** [comment]
I am trying to keep a distinction between the tool and how you use it. I believe there are some checks that foliage should do itself, to guarantee the output "makes sense". Some other checks are specific to the way you use it and can be left to the user. Of course, it's fine and fuzzy line to walk.

**Comment by andreabedini** [comment]
All this was implemented in https://github.com/input-output-hk/cardano-haskell-packages
